### ISSUE TITLE
Issue when installing on Linux

### ISSUE THREAD

**Issue by andreaseckmayr** [wakatime/texstudio-wakatime#4]
python version: 3.7.4
wakatime-cli version: 13.0.0
os: arch linux

$ curl -fsSL https://raw.githubusercontent.com/wakatime/texstudio-wakatime/master/install.py | python

Traceback (most recent call last):
  File "<stdin>", line 111, in <module>
  File "<stdin>", line 42, in main
  File "<stdin>", line 96, in find_macro_file
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10 column 5 (char 237)

**Comment by gandarez** [comment]
It seems there's a file called `Macro_{X}.txsMacro` (where X is a number) which is not a well json format. Could you please check that information in this folder `~/.config/texstudio/macro`?

**Comment by andreaseckmayr** [comment]
I got two files Marco_0.txsMacro and Macro_1.txsMacro in there, both containts following json text:
`{
    "abbrev": "",
    "description": [
        ""
    ],
    "formatVersion": 1,
    "menu": "",
    "name": "",
    "shortcut": "",
    "tag": [
        ""
    ],
    "trigger": ""
}`

**Comment by gandarez** [comment]
Could you please attach them here?

**Comment by andreaseckmayr** [comment]
[Macro_.zip](https://github.com/wakatime/texstudio-wakatime/files/3775902/Macro_.zip)

**Comment by gandarez** [comment]
As soon as they are empty ones please delete those files from the directory and try running `install.py` again.

**Comment by andreaseckmayr** [comment]
After deleting the files I got the same error, however the file is now looking different and definitely no valid json:
`{
  "abbrev": "",
  "description": "TeXstudio macro for automatic time tracking and metrics generated from your TeXstudio usage.",
  "formatVersion": 1,
  "menu": "",
  "name": "WakaTime",
  "shortcut": "",
  "tag": [
    "%SCRIPT",
    `

[Macro_0.zip](https://github.com/wakatime/texstudio-wakatime/files/3775945/Macro_0.zip)

**Comment by gandarez** [comment]
It's failling exactly at the point of reading files from the source. Try running with `sudo`.

**Comment by andreaseckmayr** [comment]
Running with sudo gives me another error:

Traceback (most recent call last):
  File "<stdin>", line 111, in <module>
  File "<stdin>", line 43, in main
  File "<stdin>", line 107, in save_macro_file
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

**Comment by gandarez** [comment]
The python version you're using is not supported at this time. Please use ` Python 2.7` instead.

**Comment by andreaseckmayr** [comment]
Thanks. Running with `Python 2.7` and `sudo` after deleting all macro files solved it. I'm closing the issue.
